### ISSUE TITLE
Unable to find image 'tensorflow-ll-stack:latest' locally

### ISSUE THREAD

**Issue by Adsyarif** [jonkrohn/DLTFpT#5]
I have problem with Unable to find image 'tensorflow-ll-stack:latest' locally.
This problem comes up when Im excecuting

docker run -v c:/full/path/to/the/clone:/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack

**Comment by jonkrohn** [comment]
Hi @Adsyarif, glad to have you over at this new repo!

I think your issue is the same as [this existing one](https://github.com/jonkrohn/DLTFpT/issues/4). I've provided a resolution there that has worked for other users. Hopefully I'll have time over the next few days to formally update the instructions in this repo to detail usage of the Docker image I've already built instead of you needing to create the Docker image yourself.

**Comment by Adsyarif** [comment]
it still dosent work. If im wrong with the command line. I just copy and paste from the guidelines
` docker run -v %cd%:/home/jovyan/work -it --rm -p 8888:8888 dltfpt-stack`

PS C:\Users\adris\OneDrive\Documents\DLTFpT> docker run -v %cd%:/home/jovyan/work -it --rm -p 8888:8888 dltfpt-stack
docker: Error response from daemon: create %cd%: "%cd%" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Comment by jonkrohn** [comment]
Oh I just realized you're running Windows. That is tricky for me to debug as I don't have access to a Windows machine.

That said, I'm still pretty sure the `docker run` step (Step 6 in the [Windows installation instructions](https://github.com/jonkrohn/DLTFpT/blob/master/installation/windows_step_by_step.md)) isn't the issue. I think it was the preceding step (Step 5).

Earlier tonight, I updated Step 5 from being a `docker build` call to a `docker pull` call. Have you run the new Step 5 in the Windows instructions? That is: `docker pull jonkrohn/dltfpt-stack:videos`

**Comment by jonkrohn** [comment]
A few other ideas in case you continue to run into issues, @Adsyarif: 

1. Perhaps StackOverflow or some tutorial can provide guidance on how to run the command line / resolve your error on Windows? Regrettably, I haven't used Windows in several decades so can't be of much help. It seems like the most recent error you're getting is related to specifying the path correctly, so might be easy to fix with someone who knows the Windows command line.
2. Could you use [Google Colab](https://colab.research.google.com/) in the cloud instead of installing the Jupyter notebooks locally? That's my number-one way of working with the notebooks in this repo anyway.
3. Could you install Ubuntu (a popular Unix OS) as a dual-boot OS on your Windows machine? You'll find that super helpful for lots of machine learning software in the future anyway.
